novel         : Green Mud
book          : Dancing Without Architecture
book_slug     : dancing
chapter_slug  : frontmatter
extra_styles  : chapters/dancing.css
voice         : narrator

chapters:
    -   name: 'In Which JJ.'
        url: 'in-which-jj/'
    -   name: 'Daymares, Poor Boy.'
        url: 'daymares/'
    - name: 'The Susy Within.'
    - name: 'Yes Mother, Goodnight.'
    - name: 'Bring Down The House House.'
    - name: 'Dance Together And Cry.'
    - name: 'Forever Amen.'
    - name: 'Twice Three, Plus One.'
    - name: 'Love In A Time Of Dandelions.'
    - name: 'Partly Cloudy.'
    - name: 'Those Nice Bright Colors.'
    - name: 'Into The Green Green Mud.'
    - name: 'Given time, silence.'