chapter: Daymares, Poor Boy.
chapter_slug: daymares-poor-boy
description: 'Chapter 2: Daymares, Poor Boy.'
extra_styles: dancing-without-architecture/daymares-poor-boy.css
next_chapter: ../the-susy-within/
prev_chapter: ../in-which-jj/
