chapter: This Road Full Glittered.
chapter_slug: this-road-full-glittered
description: 'Chapter 25: This Road Full Glittered.'
extra_styles: this-everafter-life/this-road-full-glittered.css
next_chapter: ../over-un-thought-waters/
prev_chapter: whence-from-two/
