chapter: Yes Mother, Goodnight.
chapter_slug: yes-mother-goodnight
description: 'Chapter 4: Yes Mother, Goodnight.'
extra_styles: dancing-without-architecture/yes-mother-goodnight.css
next_chapter: ../bring-down-the-house-house/
prev_chapter: ../the-susy-within/
