chapter: Bring Down the House House.
chapter_slug: bring-down-the-house-house
description: 'Chapter 5: Bring Down the House House.'
extra_styles: dancing-without-architecture/bring-down-the-house-house.css
next_chapter: ../dance-together-and-cry/
prev_chapter: ../yes-mother-goodnight/
voice: jj
