chapter: Open and Empty.
chapter_slug: open-and-empty
description: 'Chapter 15: Open and Empty.'
extra_styles: this-everafter-life/open-and-empty.css
next_chapter: ../not-a-susy-in-sight-for-miles-and-miles/
prev_chapter: ./
