chapter: Once upon a Sunday Raining.
chapter_slug: once-upon-a-sunday-raining
description: 'Chapter 14: Once upon a Sunday Raining.'
extra_styles: this-everafter-life/once-upon-a-sunday-raining.css
next_chapter: ../open-and-empty/
prev_chapter: stranger-than-a-sunny-day-on-the-beach/
voice: susy
