book          : Into the Green Green Mud
description   : Into the Green Green Mud

extends: novel/page.j2
default_block: page

chapter_slug: frontmatter
extra_styles: chapters/frontmatter.css
voice: narrator
