chapter: Love in the Time of Dandelions.
chapter_slug: love-in-the-time-of-dandelions
description: 'Chapter 9: Love in the Time of Dandelions.'
extra_styles: dancing-without-architecture/love-in-the-time-of-dandelions.css
next_chapter: ../those-nice-bright-colors/
prev_chapter: ./
voice: jj
