chapter: Why Cry when You Can Kick a Cat?
chapter_slug: why-cry-when-you-can-kick-a-cat
description: 'Chapter 19: Why Cry when You Can Kick a Cat?'
extra_styles: this-everafter-life/why-cry-when-you-can-kick-a-cat.css
next_chapter: ../there-and-back-again-forever/
prev_chapter: ./
