chapter: Under the Sky is Gray.
chapter_slug: under-the-sky-is-gray
description: 'Chapter 22: Under the Sky is Gray.'
extra_styles: this-everafter-life/under-the-sky-is-gray.css
next_chapter: ../still/
prev_chapter: ../nothing/
voice: susy
