chapter: Dance Together and Cry.
chapter_slug: dance-together-and-cry
description: 'Chapter 6: Dance Together and Cry.'
extra_styles: dancing-without-architecture/dance-together-and-cry.css
next_chapter: ../forever-amen/
prev_chapter: ../bring-down-the-house-house/
