chapter: Stranger Than a Sunny Day on the Beach.
chapter_slug: stranger-than-a-sunny-day-on-the-beach
description: 'Chapter 13: Stranger Than a Sunny Day on the Beach.'
extra_styles: this-everafter-life/stranger-than-a-sunny-day-on-the-beach.css
next_chapter: ../once-upon-a-sunday-raining/
prev_chapter: ../
