chapter: Not a Susy in Sight for Miles and Miles
chapter_slug: not-a-susy-in-sight-for-miles-and-miles
description: 'Chapter 16: Not a Susy in Sight for Miles and Miles'
extra_styles: this-everafter-life/not-a-susy-in-sight-for-miles-and-miles.css
next_chapter: ../of-blood/
prev_chapter: ./
voice: jj
