chapter: Forever Amen.
chapter_slug: forever-amen
description: 'Chapter 7: Forever Amen.'
extra_styles: dancing-without-architecture/forever-amen.css
next_chapter: ../twice-three-plus-one/
prev_chapter: dance-together-and-cry/
voice: susy
