chapter: Whence, from Two
chapter_slug: whence-from-two
description: 'Chapter 24: Whence, from Two'
extra_styles: this-everafter-life/whence-from-two.css
next_chapter: ../this-road-full-glittered/
prev_chapter: ./
