chapter: Those Nice Bright Colors.
chapter_slug: those-nice-bright-colors
description: 'Chapter 10: Those Nice Bright Colors.'
extra_styles: dancing-without-architecture/those-nice-bright-colors.css
next_chapter: ../into-the-green-green-mud/
prev_chapter: ./
