chapter: Anon and Anon.
chapter_slug: anon-and-anon
description: 'Chapter 18: Anon and Anon.'
extra_styles: this-everafter-life/anon-and-anon.css
next_chapter: ../why-cry-when-you-can-kick-a-cat/
prev_chapter: ../of-blood/
voice: susy
