chapter: Into the Green Green Mud.
chapter_slug: into-the-green-green-mud
description: 'Chapter 11: Into the Green Green Mud.'
extra_styles: dancing-without-architecture/into-the-green-green-mud.css
next_chapter: ../given-time-silence/
prev_chapter: those-nice-bright-colors/
voice: jj
